export const CLayerEvent = {
    ENABLE_LOBBY: "ENABLE_LOBBY",
    DISABLE_LOBBY: "DISABLE_LOBBY",

    ENABLE_ROOM: "ENABLE_ROOM",
    INIT_ROOM: "INIT_ROOM",
    DISABLE_ROOM: "DISABLE_ROOM",

    ENABLE_POPUP: "ENABLE_POPUP",
    DISABLE_POPUP: "DISABLE_POPUP",
}