export const CRoundEvent = {
    INIT_ROUND: 'INIT_ROUND',
    RESET_ROUND: 'RESET_ROUND',
    SPAWN_ENEMY: 'SPAWN_ENEMY',
    PLAYER_TAKE_DAMAGE: 'PLAYER_TAKE_DAMAGE',
    ENEMY_TAKE_DAMAGE: 'ENEMY_TAKE_DAMAGE',
}